### ISSUE TITLE
Where is the 1/4 and full label experiments?

### ISSUE THREAD

**Issue by TyroneLi** [Jia-Research-Lab/Context-Aware-Consistency#16] opened 2021-08-09 02:39 UTC
It seems that you only provide 1323 label supervised experiment. How can I reimplement your 1/4 and full part?? Thanks

**Comment by X-Lai** [comment] 2021-08-09 08:51
You can customize the config on your own. If your want to reproduce the results of 1/4 labeled data, you can change the `n_labeled_examples` to 2645. As for the Full setting, you need modify the codes to use all data as the labeled data, and all images as the unlabeled data.

**Comment by TyroneLi** [comment] 2021-08-10 02:29
> You can customize the config on your own. If your want to reproduce the results of 1/4 labeled data, you can change the `n_labeled_examples` to 2645. As for the Full setting, you need modify the codes to use all data as the labeled data, and all images as the unlabeled data.

Emmm, I simply change `n_labeled_examples` into 2645 and 10582，but only get nearly 74% mIoU while training. So you means I should also modify the codes to use all data as the labeled data, and all images as the unlabeled data, and this part remains unchange??

**Comment by X-Lai** [comment] 2021-08-10 02:49
Using only 2645 is a semi-supervised setting, so in this case, you don't need to modify the codes. If you want use 10582 samples, where the case is different from the semi-supervised setting, so you need to modify the codes on your own.

As for your reported 74% miou performance, do you mean the result of using 2645 samples on the datalist0? Can you elaborate more concretely? Or give me your log file?

**Comment by TyroneLi** [comment] 2021-08-10 08:19
> Using only 2645 is a semi-supervised setting, so in this case, you don't need to modify the codes. If you want use 10582 samples, where the case is different from the semi-supervised setting, so you need to modify the codes on your own.
> 
> As for your reported 74% miou performance, do you mean the result of using 2645 samples on the datalist0? Can you elaborate more concretely? Or give me your log file?

Since the overall training epoch is not done yet for only 2645 semi-supervised setting, I will provide my own log here. For 10582 full labeled setting, I just want to reimplement your report data at Table 1 Full column. I simply modify the `n_labeled_examples` at config file, could you provide more details for Table 1 column `Full` part?

**Comment by X-Lai** [comment] 2021-08-10 14:32
For the full-data setting, you need to use all the images and labels as the labeled data to calculate the CE Loss, and all the images as the unlabeled data to calculate the Contrastive Loss, since there is no unlabeled images in this setting.

**Comment by X-Lai** [comment] 2021-08-12 02:50
I will close this issue. If you have further question, feel free to reopen it.

**Closed as completed by X-Lai** 2021-08-12 02:50 UTC
